### ISSUE TITLE
Snyk vulnerability -  Improper Input Validation

### ISSUE THREAD

**Issue by skvijay007** [unshiftio/original#23]
https://snyk.io/vuln/SNYK-JS-URLPARSE-1078283

**Comment by lpinca** [comment]
This was fixed by https://github.com/unshiftio/original/pull/22.

**Comment by Blackbaud-ChristiSchneider** [comment]
Do you have an anticipated date on when a version with this fix will be released?

**Comment by lpinca** [comment]
The latest published version is already ok as per https://github.com/unshiftio/original/blob/1.0.2/package.json#L25. Update or regenerate your lock file.

**Comment by Blackbaud-ChristiSchneider** [comment]
Oh sorry, I didn't see the carat. Thanks!
